on: [push]

name: test


jobs:
  ubuntu:
    strategy:
      fail-fast: false
    container: 'ghcr.io/f4pga/prjxray/ci'
    runs-on: [self-hosted, Linux, X64]
    env:
      TEST_STRING: "VERY_COOL_STRING"
      TEST_STRING2: "VERY_COOL_STRING2"
      MATRIX_PASS: ${{ matrix.tag }}
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Setup repository
      uses: actions/checkout@v2
    - run: |
        echo $GITHUB_STEP_SUMMARY
        echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
        ls -la $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v2
      with:
        path: |
          **/*.txt
          **/plot_*.svg
