on: [push]

name: test


jobs:
  CompositeLocal-Custom:
    container: ubuntu:bionic
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - uses: actions/checkout@v3
      - uses: ./composite
  CompositeLocal-Custom-2:
    container: ubuntu:bionic
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - uses: actions/checkout@v3
      - uses: ./composite/rundir/
  CompositeLocal-Custom-3:
    container: ubuntu:bionic
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - uses: actions/checkout@v3
      - uses: ./composite2
